server.port: 8097

spring:
  main:
    banner-mode: console
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:BOOKING_INGESTION_DB
    username: books
    password: books
    driver-class-name: oracle.jdbc.OracleDriver
  flyway:
    url: jdbc:oracle:thin:@localhost:1521:BOOKING_INGESTION_DB
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="password";
      security.protocol: SASL_PLAINTEXT
      schema.registry.url: http://localhost:9010/apis/ccompat/v7

management:
  endpoint:
    health:
      probes:
        enabled: true
